import { WeaponConfig } from './types';

export const WEAPONS: Record<string, WeaponConfig> = {
  knife: {
    id: 'knife',
    name: '战术匕首 (Knife)',
    category: 'melee',
    price: 0,
    damage: 40,
    headshotMultiplier: 1.5,
    fireRate: 2.2,
    magazineSize: 0,
    reserveAmmo: 0,
    reloadTime: 0,
    spread: 0.01,
    recoilVertical: 0.02,
    recoilHorizontal: 0.01,
    range: 2.5,
    speedMultiplier: 1.0,
    killReward: 1500,
    soundType: 'knife_slash',
    description: '近战利刃，背刺致命，移动速度最快。',
  },
  glock: {
    id: 'glock',
    name: '格洛克 18 (Glock-18)',
    category: 'pistol',
    price: 200,
    damage: 28,
    headshotMultiplier: 3.5,
    fireRate: 6.5,
    magazineSize: 20,
    reserveAmmo: 120,
    reloadTime: 2.2,
    spread: 0.03,
    recoilVertical: 0.05,
    recoilHorizontal: 0.02,
    range: 50,
    speedMultiplier: 0.98,
    teamExclusive: 'T',
    killReward: 300,
    soundType: 'pistol_light',
    description: '恐怖分子初始手枪，射速较快，弹匣容量大。',
  },
  deagle: {
    id: 'deagle',
    name: '沙漠之鹰 (Desert Eagle)',
    category: 'pistol',
    price: 700,
    damage: 63,
    headshotMultiplier: 4.0,
    fireRate: 3.8,
    magazineSize: 7,
    reserveAmmo: 35,
    reloadTime: 2.5,
    spread: 0.025,
    recoilVertical: 0.12,
    recoilHorizontal: 0.04,
    range: 80,
    speedMultiplier: 0.95,
    killReward: 300,
    soundType: 'pistol_heavy',
    description: '大威力手枪，精准单发爆头可一击毙命。',
  },
  mp5: {
    id: 'mp5',
    name: 'MP5-SD 冲锋枪',
    category: 'smg',
    price: 1500,
    damage: 27,
    headshotMultiplier: 3.8,
    fireRate: 12.5,
    magazineSize: 30,
    reserveAmmo: 120,
    reloadTime: 2.7,
    spread: 0.045,
    recoilVertical: 0.06,
    recoilHorizontal: 0.03,
    range: 60,
    speedMultiplier: 0.94,
    killReward: 600,
    soundType: 'smg_fire',
    description: '消音微型冲锋枪，跑打精准度高，击杀收益翻倍。',
  },
  ak47: {
    id: 'ak47',
    name: 'AK-47 突击步枪',
    category: 'rifle',
    price: 2700,
    damage: 36,
    headshotMultiplier: 4.0, // 1 shot headshot kills full helmet
    fireRate: 10.0,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadTime: 2.5,
    spread: 0.035,
    recoilVertical: 0.09,
    recoilHorizontal: 0.045,
    range: 120,
    speedMultiplier: 0.88,
    teamExclusive: 'T',
    killReward: 300,
    soundType: 'rifle_heavy',
    description: 'T方神兵，第一发极准，一枪爆头必死，后坐力较大。',
  },
  m4a1: {
    id: 'm4a1',
    name: 'M4A4 突击步枪',
    category: 'rifle',
    price: 3100,
    damage: 33,
    headshotMultiplier: 3.5,
    fireRate: 11.0,
    magazineSize: 30,
    reserveAmmo: 90,
    reloadTime: 2.8,
    spread: 0.028,
    recoilVertical: 0.075,
    recoilHorizontal: 0.035,
    range: 120,
    speedMultiplier: 0.9,
    teamExclusive: 'CT',
    killReward: 300,
    soundType: 'rifle_clean',
    description: 'CT方制式步枪，弹道平稳，射速优秀，中远距离压枪稳定。',
  },
  awp: {
    id: 'awp',
    name: 'AWP 狙击步枪',
    category: 'sniper',
    price: 4750,
    damage: 115,
    headshotMultiplier: 4.0,
    fireRate: 1.4,
    magazineSize: 5,
    reserveAmmo: 30,
    reloadTime: 3.6,
    spread: 0.25, // very inaccurate unscoped
    recoilVertical: 0.3,
    recoilHorizontal: 0.05,
    range: 250,
    speedMultiplier: 0.8,
    hasScope: true,
    scopeMagnification: 4.0,
    killReward: 100,
    soundType: 'sniper_boom',
    description: '高风险高回报的重型狙击步枪，击中上半身一击毙命。右键开镜。',
  },
  hegrenade: {
    id: 'hegrenade',
    name: '高爆手雷 (HE Grenade)',
    category: 'grenade',
    price: 300,
    damage: 98,
    headshotMultiplier: 1.0,
    fireRate: 1.0,
    magazineSize: 1,
    reserveAmmo: 0,
    reloadTime: 1.0,
    spread: 0.01,
    recoilVertical: 0.0,
    recoilHorizontal: 0.0,
    range: 40,
    speedMultiplier: 0.98,
    killReward: 300,
    soundType: 'grenade_pin',
    description: '造成范围爆炸伤害，清理死角与压制敌人。',
  },
  flashbang: {
    id: 'flashbang',
    name: '闪光震撼弹 (Flashbang)',
    category: 'grenade',
    price: 200,
    damage: 0,
    headshotMultiplier: 1.0,
    fireRate: 1.0,
    magazineSize: 2,
    reserveAmmo: 0,
    reloadTime: 1.0,
    spread: 0.01,
    recoilVertical: 0.0,
    recoilHorizontal: 0.0,
    range: 40,
    speedMultiplier: 0.98,
    killReward: 0,
    soundType: 'grenade_pin',
    description: '致盲视野内的所有目标，攻点必备。',
  },
  smokegrenade: {
    id: 'smokegrenade',
    name: '战术烟雾弹 (Smoke)',
    category: 'grenade',
    price: 300,
    damage: 0,
    headshotMultiplier: 1.0,
    fireRate: 1.0,
    magazineSize: 1,
    reserveAmmo: 0,
    reloadTime: 1.0,
    spread: 0.01,
    recoilVertical: 0.0,
    recoilHorizontal: 0.0,
    range: 40,
    speedMultiplier: 0.98,
    killReward: 0,
    soundType: 'grenade_pin',
    description: '展开厚重的遮挡烟雾，阻断敌方视野18秒。',
  },
  c4: {
    id: 'c4',
    name: 'C4 炸药包',
    category: 'utility',
    price: 0,
    damage: 500,
    headshotMultiplier: 1.0,
    fireRate: 0.5,
    magazineSize: 1,
    reserveAmmo: 0,
    reloadTime: 0,
    spread: 0,
    recoilVertical: 0,
    recoilHorizontal: 0,
    range: 3,
    speedMultiplier: 0.95,
    teamExclusive: 'T',
    killReward: 0,
    soundType: 'c4_beep',
    description: 'T方目标道具。在A点或B点包点按住E键安装C4炸药包。',
  },
};

export const BUY_MENU_ITEMS = [
  // Pistols
  { id: 'glock', category: '手枪 (Pistols)', item: WEAPONS.glock },
  { id: 'deagle', category: '手枪 (Pistols)', item: WEAPONS.deagle },
  // SMGs
  { id: 'mp5', category: '冲锋枪 (SMGs)', item: WEAPONS.mp5 },
  // Rifles
  { id: 'ak47', category: '步枪 (Rifles)', item: WEAPONS.ak47 },
  { id: 'm4a1', category: '步枪 (Rifles)', item: WEAPONS.m4a1 },
  { id: 'awp', category: '狙击枪 (Snipers)', item: WEAPONS.awp },
  // Equipment
  {
    id: 'kevlar',
    name: '防弹背心 (Kevlar)',
    category: '装备 (Gear)',
    price: 650,
    description: '减少受到的身体伤害',
    icon: 'shield',
  },
  {
    id: 'helmet',
    name: '防弹头盔 (Helmet + Armor)',
    category: '装备 (Gear)',
    price: 1000,
    description: '完全防止部分枪械的爆头秒杀',
    icon: 'hard-hat',
  },
  {
    id: 'defuser',
    name: '拆弹器 (Defuse Kit)',
    category: '装备 (Gear)',
    price: 400,
    description: 'CT专属，将拆除C4时间由10秒缩短至5秒',
    icon: 'wrench',
    teamExclusive: 'CT' as const,
  },
  // Grenades
  { id: 'hegrenade', category: '投掷物 (Grenades)', item: WEAPONS.hegrenade },
  { id: 'flashbang', category: '投掷物 (Grenades)', item: WEAPONS.flashbang },
  { id: 'smokegrenade', category: '投掷物 (Grenades)', item: WEAPONS.smokegrenade },
];
