/**
 * Static game data: weapons, units and structures.
 *
 * All balance numbers live here so they can be tuned in one place. Times are in simulation ticks
 * (30/s), distances in world pixels (a tile is 24px), speeds in world pixels per tick.
 */
import { seconds, TILE } from "./constants";
import {
  ArmorKind,
  ProjectileKind,
  QueueKind,
  SidebarTab,
  UnitClass,
  type StructureDef,
  type StructureKindId,
  type UnitDef,
  type UnitKindId,
  type WeaponDef,
} from "./types";

const tiles = (n: number): number => n * TILE;

/** Shorthand for a full verses row. */
function verses(
  none: number,
  wood: number,
  light: number,
  heavy: number,
  concrete: number,
): Record<ArmorKind, number> {
  return { none, wood, light, heavy, concrete };
}

// ── Weapons ─────────────────────────────────────────────────────────────────

function weapon(def: Partial<WeaponDef> & Pick<WeaponDef, "id" | "damage" | "rof" | "range">): WeaponDef {
  return {
    projectile: ProjectileKind.Instant,
    spread: 0,
    verses: verses(1, 1, 1, 1, 1),
    speed: 8,
    groundAttack: false,
    burst: 1,
    burstDelay: 3,
    ...def,
  };
}

export const WEAPONS: Record<string, WeaponDef> = {
  /** Small arms: shreds infantry, useless against armour. */
  rifle: weapon({
    id: "rifle",
    damage: 14,
    rof: 24,
    range: tiles(3.5),
    projectile: ProjectileKind.Instant,
    verses: verses(1.0, 0.5, 0.25, 0.05, 0.03),
    burst: 2,
    burstDelay: 4,
  }),
  /** Ranger / pillbox machine gun. */
  mg: weapon({
    id: "mg",
    damage: 12,
    rof: 16,
    range: tiles(4),
    projectile: ProjectileKind.Instant,
    verses: verses(1.0, 0.5, 0.35, 0.08, 0.05),
    burst: 3,
    burstDelay: 3,
  }),
  /** Grenade: lobbed, splash, good against buildings. */
  grenade: weapon({
    id: "grenade",
    damage: 45,
    rof: 45,
    range: tiles(4),
    projectile: ProjectileKind.Lobbed,
    spread: tiles(0.9),
    speed: 3.2,
    groundAttack: true,
    verses: verses(0.9, 1.0, 0.6, 0.3, 0.85),
  }),
  /** Anti-armour rocket. */
  rocket: weapon({
    id: "rocket",
    damage: 42,
    rof: 52,
    range: tiles(5.5),
    projectile: ProjectileKind.Missile,
    spread: tiles(0.4),
    speed: 4.5,
    verses: verses(0.4, 0.7, 0.9, 1.0, 0.8),
  }),
  /** Main tank gun. */
  apShell: weapon({
    id: "apShell",
    damage: 34,
    rof: 42,
    range: tiles(5),
    projectile: ProjectileKind.Ballistic,
    spread: tiles(0.3),
    speed: 9,
    groundAttack: true,
    verses: verses(0.35, 0.6, 0.9, 1.0, 0.55),
  }),
  /** Allied light tank gun — faster but weaker. */
  apShellLight: weapon({
    id: "apShellLight",
    damage: 22,
    rof: 34,
    range: tiles(4.5),
    projectile: ProjectileKind.Ballistic,
    spread: tiles(0.25),
    speed: 9,
    groundAttack: true,
    verses: verses(0.35, 0.6, 0.9, 0.9, 0.5),
  }),
  /** Mammoth twin cannon. */
  apShellHeavy: weapon({
    id: "apShellHeavy",
    damage: 40,
    rof: 60,
    range: tiles(5.5),
    projectile: ProjectileKind.Ballistic,
    spread: tiles(0.35),
    speed: 9,
    groundAttack: true,
    burst: 2,
    burstDelay: 6,
    verses: verses(0.4, 0.7, 0.95, 1.0, 0.6),
  }),
  /** Mammoth secondary rocket pod. */
  mammothTusk: weapon({
    id: "mammothTusk",
    damage: 30,
    rof: 80,
    range: tiles(5),
    projectile: ProjectileKind.Missile,
    spread: tiles(0.5),
    speed: 4.2,
    burst: 2,
    burstDelay: 5,
    verses: verses(0.8, 0.8, 0.8, 0.7, 0.6),
  }),
  /** V2 / artillery: long range, heavy splash, slow. */
  v2rocket: weapon({
    id: "v2rocket",
    damage: 90,
    rof: seconds(6),
    range: tiles(10),
    projectile: ProjectileKind.Missile,
    spread: tiles(1.6),
    speed: 3.4,
    groundAttack: true,
    verses: verses(0.9, 1.0, 0.75, 0.45, 1.0),
  }),
  artillery: weapon({
    id: "artillery",
    damage: 70,
    rof: seconds(4.5),
    range: tiles(9),
    projectile: ProjectileKind.Lobbed,
    spread: tiles(1.4),
    speed: 3.0,
    groundAttack: true,
    verses: verses(0.9, 1.0, 0.7, 0.4, 0.95),
  }),
  /** Tesla Coil: devastating, short-ish range, power hungry. */
  tesla: weapon({
    id: "tesla",
    damage: 95,
    rof: seconds(2.2),
    range: tiles(6),
    projectile: ProjectileKind.Instant,
    spread: 0,
    verses: verses(1.0, 1.0, 1.0, 0.9, 0.55),
  }),
  /** Flame Tower cone. */
  flame: weapon({
    id: "flame",
    damage: 26,
    rof: 18,
    range: tiles(3),
    projectile: ProjectileKind.Flame,
    spread: tiles(0.8),
    speed: 5,
    groundAttack: true,
    verses: verses(1.0, 1.0, 0.5, 0.22, 0.35),
  }),
  /** Attack dog: instantly kills infantry, cannot hurt anything else. */
  dogJaw: weapon({
    id: "dogJaw",
    damage: 130,
    rof: 30,
    range: tiles(0.9),
    projectile: ProjectileKind.Instant,
    verses: verses(1.0, 0, 0, 0, 0),
  }),
  /** Nuclear warhead. Flattens everything inside a wide radius, concrete included. */
  nuke: weapon({
    id: "nuke",
    damage: 1200,
    rof: 1,
    range: 0,
    projectile: ProjectileKind.Lobbed,
    spread: tiles(6),
    speed: 1,
    groundAttack: true,
    verses: verses(1, 1, 1, 1, 1),
  }),
  /** Allied gun turret. */
  turretGun: weapon({
    id: "turretGun",
    damage: 30,
    rof: 40,
    range: tiles(5.5),
    projectile: ProjectileKind.Ballistic,
    spread: tiles(0.3),
    speed: 9,
    verses: verses(0.4, 0.6, 0.9, 0.95, 0.5),
  }),
};

// ── Units ───────────────────────────────────────────────────────────────────

function unit(def: Partial<UnitDef> & Pick<UnitDef, "id" | "cls" | "side" | "cost" | "hp">): UnitDef {
  const infantry = def.cls === UnitClass.Infantry;
  return {
    buildTime: seconds(def.cost / 80),
    armor: infantry ? ArmorKind.None : ArmorKind.Light,
    speed: infantry ? 0.85 : 1.4,
    turnRate: infantry ? 0.6 : 0.12,
    turretTurnRate: 0.1,
    hasTurret: false,
    weapon: null,
    weapon2: null,
    sight: 5,
    radius: infantry ? 5 : 9,
    producedBy: null,
    requires: [],
    cargoCapacity: 0,
    crusher: false,
    selfHeal: 0,
    order: 0,
    ...def,
  };
}

export const UNITS: Record<UnitKindId, UnitDef> = {
  // ── Soviet ────────────────────────────────────────────────────────────────
  e1: unit({
    id: "e1",
    cls: UnitClass.Infantry,
    side: "soviet",
    cost: 100,
    hp: 80,
    weapon: "rifle",
    sight: 5,
    producedBy: "barracks",
    requires: ["barracks"],
    order: 10,
  }),
  e2: unit({
    id: "e2",
    cls: UnitClass.Infantry,
    side: "soviet",
    cost: 160,
    hp: 90,
    speed: 0.78,
    weapon: "grenade",
    producedBy: "barracks",
    requires: ["barracks"],
    order: 20,
  }),
  e3: unit({
    id: "e3",
    cls: UnitClass.Infantry,
    side: "soviet",
    cost: 300,
    hp: 90,
    speed: 0.72,
    weapon: "rocket",
    sight: 6,
    producedBy: "barracks",
    requires: ["barracks"],
    order: 30,
  }),
  e6: unit({
    id: "e6",
    cls: UnitClass.Infantry,
    side: "soviet",
    cost: 500,
    hp: 60,
    speed: 0.95,
    sight: 4,
    producedBy: "barracks",
    requires: ["barracks"],
    order: 40,
  }),
  dog: unit({
    id: "dog",
    cls: UnitClass.Infantry,
    side: "soviet",
    cost: 200,
    hp: 60,
    speed: 2.1,
    turnRate: 0.9,
    weapon: "dogJaw",
    sight: 6,
    radius: 4,
    producedBy: "kennel",
    requires: ["kennel"],
    order: 50,
  }),
  harv: unit({
    id: "harv",
    cls: UnitClass.Vehicle,
    side: "soviet",
    cost: 1400,
    hp: 600,
    armor: ArmorKind.Heavy,
    speed: 1.15,
    turnRate: 0.09,
    sight: 4,
    radius: 11,
    cargoCapacity: 20,
    crusher: true,
    producedBy: "warfactory",
    requires: ["warfactory", "refinery"],
    order: 10,
  }),
  "3tnk": unit({
    id: "3tnk",
    cls: UnitClass.Vehicle,
    side: "soviet",
    cost: 950,
    hp: 550,
    armor: ArmorKind.Heavy,
    speed: 1.3,
    turnRate: 0.1,
    turretTurnRate: 0.13,
    hasTurret: true,
    weapon: "apShell",
    sight: 6,
    radius: 10,
    crusher: true,
    producedBy: "warfactory",
    requires: ["warfactory"],
    order: 20,
  }),
  "4tnk": unit({
    id: "4tnk",
    cls: UnitClass.Vehicle,
    side: "soviet",
    cost: 1700,
    hp: 950,
    armor: ArmorKind.Heavy,
    speed: 0.85,
    turnRate: 0.07,
    turretTurnRate: 0.09,
    hasTurret: true,
    weapon: "apShellHeavy",
    weapon2: "mammothTusk",
    sight: 7,
    radius: 12,
    crusher: true,
    selfHeal: 0.05,
    producedBy: "warfactory",
    requires: ["warfactory", "radar"],
    order: 40,
  }),
  v2rl: unit({
    id: "v2rl",
    cls: UnitClass.Vehicle,
    side: "soviet",
    cost: 700,
    hp: 260,
    armor: ArmorKind.Light,
    speed: 1.05,
    turnRate: 0.09,
    hasTurret: false,
    weapon: "v2rocket",
    sight: 6,
    radius: 10,
    producedBy: "warfactory",
    requires: ["warfactory", "radar"],
    order: 30,
  }),
  mcv: unit({
    id: "mcv",
    cls: UnitClass.Vehicle,
    side: "both",
    cost: 2500,
    hp: 900,
    armor: ArmorKind.Heavy,
    speed: 0.8,
    turnRate: 0.07,
    sight: 5,
    radius: 13,
    producedBy: "warfactory",
    requires: ["warfactory", "radar"],
    order: 50,
  }),

  // ── Allied (AI) ───────────────────────────────────────────────────────────
  e1a: unit({
    id: "e1a",
    cls: UnitClass.Infantry,
    side: "allied",
    cost: 100,
    hp: 80,
    weapon: "rifle",
    producedBy: "barracks_a",
    requires: ["barracks_a"],
    order: 10,
  }),
  e3a: unit({
    id: "e3a",
    cls: UnitClass.Infantry,
    side: "allied",
    cost: 300,
    hp: 90,
    speed: 0.72,
    weapon: "rocket",
    sight: 6,
    producedBy: "barracks_a",
    requires: ["barracks_a"],
    order: 20,
  }),
  jeep: unit({
    id: "jeep",
    cls: UnitClass.Vehicle,
    side: "allied",
    cost: 600,
    hp: 220,
    armor: ArmorKind.Light,
    speed: 2.3,
    turnRate: 0.16,
    turretTurnRate: 0.2,
    hasTurret: true,
    weapon: "mg",
    sight: 7,
    radius: 8,
    producedBy: "warfactory_a",
    requires: ["warfactory_a"],
    order: 10,
  }),
  "1tnk": unit({
    id: "1tnk",
    cls: UnitClass.Vehicle,
    side: "allied",
    cost: 700,
    hp: 400,
    armor: ArmorKind.Heavy,
    speed: 1.6,
    turnRate: 0.12,
    turretTurnRate: 0.15,
    hasTurret: true,
    weapon: "apShellLight",
    sight: 6,
    radius: 9,
    crusher: true,
    producedBy: "warfactory_a",
    requires: ["warfactory_a"],
    order: 20,
  }),
  "2tnk": unit({
    id: "2tnk",
    cls: UnitClass.Vehicle,
    side: "allied",
    cost: 900,
    hp: 500,
    armor: ArmorKind.Heavy,
    speed: 1.35,
    turnRate: 0.1,
    turretTurnRate: 0.13,
    hasTurret: true,
    weapon: "apShell",
    sight: 6,
    radius: 10,
    crusher: true,
    producedBy: "warfactory_a",
    requires: ["warfactory_a"],
    order: 30,
  }),
  arty: unit({
    id: "arty",
    cls: UnitClass.Vehicle,
    side: "allied",
    cost: 600,
    hp: 200,
    armor: ArmorKind.Light,
    speed: 1.0,
    turnRate: 0.08,
    weapon: "artillery",
    sight: 6,
    radius: 9,
    producedBy: "warfactory_a",
    requires: ["warfactory_a"],
    order: 40,
  }),
  harva: unit({
    id: "harva",
    cls: UnitClass.Vehicle,
    side: "allied",
    cost: 1400,
    hp: 600,
    armor: ArmorKind.Heavy,
    speed: 1.15,
    turnRate: 0.09,
    sight: 4,
    radius: 11,
    cargoCapacity: 20,
    crusher: true,
    producedBy: "warfactory_a",
    requires: ["warfactory_a", "refinery_a"],
    order: 5,
  }),
};

// ── Structures ──────────────────────────────────────────────────────────────

function structure(
  def: Partial<StructureDef> & Pick<StructureDef, "id" | "side" | "cost" | "hp" | "w" | "h">,
): StructureDef {
  return {
    buildTime: seconds(Math.max(2, def.cost / 120)),
    armor: ArmorKind.Concrete,
    powerProduced: 0,
    powerConsumed: 0,
    weapon: null,
    hasTurret: false,
    turretTurnRate: 0.12,
    sight: 6,
    requires: [],
    providesRadar: false,
    storage: 0,
    isRefinery: false,
    producesQueue: null,
    exit: null,
    tab: SidebarTab.Structures,
    order: 0,
    superweaponCharge: 0,
    ...def,
  };
}

export const STRUCTURES: Record<StructureKindId, StructureDef> = {
  // ── Soviet ────────────────────────────────────────────────────────────────
  conyard: structure({
    id: "conyard",
    side: "soviet",
    cost: 2500,
    hp: 4000,
    w: 3,
    h: 3,
    sight: 8,
    storage: 1000,
    producesQueue: QueueKind.Structure,
    order: 0,
  }),
  power: structure({
    id: "power",
    side: "soviet",
    cost: 300,
    hp: 800,
    w: 2,
    h: 2,
    powerProduced: 100,
    requires: ["conyard"],
    tab: SidebarTab.Structures,
    order: 10,
  }),
  refinery: structure({
    id: "refinery",
    side: "soviet",
    cost: 2000,
    hp: 1400,
    w: 3,
    h: 2,
    powerConsumed: 30,
    storage: 2000,
    isRefinery: true,
    requires: ["power"],
    exit: { tx: 3, ty: 1 },
    order: 20,
  }),
  silo: structure({
    id: "silo",
    side: "soviet",
    cost: 150,
    hp: 500,
    w: 2,
    h: 2,
    powerConsumed: 10,
    storage: 1500,
    requires: ["refinery"],
    order: 30,
  }),
  barracks: structure({
    id: "barracks",
    side: "soviet",
    cost: 400,
    hp: 900,
    w: 2,
    h: 2,
    powerConsumed: 20,
    requires: ["power"],
    producesQueue: QueueKind.Infantry,
    exit: { tx: 0, ty: 2 },
    order: 40,
  }),
  kennel: structure({
    id: "kennel",
    side: "soviet",
    cost: 200,
    hp: 500,
    w: 2,
    h: 2,
    powerConsumed: 10,
    requires: ["barracks"],
    exit: { tx: 0, ty: 2 },
    order: 50,
  }),
  warfactory: structure({
    id: "warfactory",
    side: "soviet",
    cost: 2000,
    hp: 1600,
    w: 3,
    h: 2,
    powerConsumed: 30,
    requires: ["refinery"],
    producesQueue: QueueKind.Vehicle,
    exit: { tx: 1, ty: 2 },
    order: 60,
  }),
  radar: structure({
    id: "radar",
    side: "soviet",
    cost: 1000,
    hp: 1000,
    w: 2,
    h: 2,
    powerConsumed: 40,
    sight: 10,
    providesRadar: true,
    requires: ["refinery"],
    order: 70,
  }),
  depot: structure({
    id: "depot",
    side: "soviet",
    cost: 1200,
    hp: 1000,
    w: 3,
    h: 2,
    powerConsumed: 30,
    requires: ["warfactory"],
    order: 80,
  }),
  nukesilo: structure({
    id: "nukesilo",
    side: "soviet",
    cost: 2500,
    hp: 1500,
    w: 2,
    h: 2,
    powerConsumed: 150,
    requires: ["tesla", "depot"],
    superweaponCharge: seconds(300),
    order: 90,
  }),

  // ── Soviet defence ────────────────────────────────────────────────────────
  wall: structure({
    id: "wall",
    side: "both",
    cost: 100,
    hp: 400,
    w: 1,
    h: 1,
    buildTime: seconds(1),
    armor: ArmorKind.Concrete,
    sight: 1,
    requires: ["conyard"],
    tab: SidebarTab.Defense,
    order: 0,
  }),
  flametower: structure({
    id: "flametower",
    side: "soviet",
    cost: 600,
    hp: 700,
    w: 1,
    h: 1,
    powerConsumed: 20,
    weapon: "flame",
    hasTurret: true,
    turretTurnRate: 0.14,
    sight: 6,
    requires: ["barracks"],
    tab: SidebarTab.Defense,
    order: 10,
  }),
  tesla: structure({
    id: "tesla",
    side: "soviet",
    cost: 1500,
    hp: 800,
    w: 1,
    h: 2,
    powerConsumed: 100,
    weapon: "tesla",
    sight: 8,
    requires: ["radar"],
    tab: SidebarTab.Defense,
    order: 20,
  }),

  // ── Allied (AI) ───────────────────────────────────────────────────────────
  conyard_a: structure({
    id: "conyard_a",
    side: "allied",
    cost: 2500,
    hp: 4000,
    w: 3,
    h: 3,
    sight: 8,
    storage: 1000,
    producesQueue: QueueKind.Structure,
  }),
  power_a: structure({
    id: "power_a",
    side: "allied",
    cost: 300,
    hp: 800,
    w: 2,
    h: 2,
    powerProduced: 100,
    requires: ["conyard_a"],
  }),
  refinery_a: structure({
    id: "refinery_a",
    side: "allied",
    cost: 2000,
    hp: 1400,
    w: 3,
    h: 2,
    powerConsumed: 30,
    storage: 2000,
    isRefinery: true,
    requires: ["power_a"],
    exit: { tx: 3, ty: 1 },
  }),
  barracks_a: structure({
    id: "barracks_a",
    side: "allied",
    cost: 400,
    hp: 900,
    w: 2,
    h: 2,
    powerConsumed: 20,
    requires: ["power_a"],
    producesQueue: QueueKind.Infantry,
    exit: { tx: 0, ty: 2 },
  }),
  warfactory_a: structure({
    id: "warfactory_a",
    side: "allied",
    cost: 2000,
    hp: 1600,
    w: 3,
    h: 2,
    powerConsumed: 30,
    requires: ["refinery_a"],
    producesQueue: QueueKind.Vehicle,
    exit: { tx: 1, ty: 2 },
  }),
  pillbox: structure({
    id: "pillbox",
    side: "allied",
    cost: 400,
    hp: 500,
    w: 1,
    h: 1,
    armor: ArmorKind.Wood,
    weapon: "mg",
    sight: 6,
    requires: ["barracks_a"],
    tab: SidebarTab.Defense,
  }),
  turret: structure({
    id: "turret",
    side: "allied",
    cost: 600,
    hp: 600,
    w: 1,
    h: 1,
    weapon: "turretGun",
    hasTurret: true,
    sight: 6,
    requires: ["barracks_a"],
    tab: SidebarTab.Defense,
  }),
};

// ── Lookups ─────────────────────────────────────────────────────────────────

export function unitDef(id: UnitKindId): UnitDef {
  return UNITS[id];
}

export function structureDef(id: StructureKindId): StructureDef {
  return STRUCTURES[id];
}

export function weaponDef(id: string): WeaponDef {
  const w = WEAPONS[id];
  if (!w) throw new Error(`Unknown weapon: ${id}`);
  return w;
}

export function isUnitKind(id: string): id is UnitKindId {
  return Object.prototype.hasOwnProperty.call(UNITS, id);
}

export function isStructureKind(id: string): id is StructureKindId {
  return Object.prototype.hasOwnProperty.call(STRUCTURES, id);
}

/** Everything the given side can ever build, sorted for the sidebar. */
export function buildableStructures(side: "soviet" | "allied"): StructureDef[] {
  return Object.values(STRUCTURES)
    .filter((s) => (s.side === side || s.side === "both") && s.id !== "conyard" && s.id !== "conyard_a")
    .sort((a, b) => a.order - b.order);
}

export function buildableUnits(side: "soviet" | "allied"): UnitDef[] {
  return Object.values(UNITS)
    .filter((u) => u.side === side || u.side === "both")
    .sort((a, b) => a.order - b.order);
}

export function damageAgainst(w: WeaponDef, armor: ArmorKind): number {
  return w.damage * w.verses[armor];
}
